// <auto-generated />
namespace OnlineShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changestreetandcityintoaddressandpostcodeinorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changestreetandcityintoaddressandpostcodeinorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202009101300428_Change street and city into address and post code in order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
